### ISSUE TITLE
Make converter compatible with bem-xjst 4+

### ISSUE THREAD

**Issue by vkz** [vkz/bemhtml-syntax#13]
see https://github.yandex-team.ru/lego/islands/pull/509
Compatibility with the latest bem-xjst should be available with relevant flag in the API
- [x] assert that every template has sub-predicate matching `block`
- [x] assert there're no predicates matching `this.elem` https://github.com/bem/bem-xjst/issues/89
- [x] assert that every `apply` sets the mode as its first argument https://github.com/bem/bem-xjst/issues/91
- [x] warn when `apply` assigns `block`, `elem`, `mods`, `elemMods` https://github.com/bem/bem-xjst/issues/73
- [x] convert `def()` + `applyCtx` with `this.ctx` inside into `wrap()` see article7 in https://github.yandex-team.ru/lego/islands/pull/509
- [x] ensure there's always `return` in `def` mode. Insert `return ''` when there is none
- [x] assert `this._buf` is never used in templates

**Comment by vkz** [comment]
`apply()` checks test:

``` js
  block b1 {
    default: { apply({test: 42, elemMods: 'bla'});}
  }
```
