### ISSUE TITLE
Add tests for bem-xjst4 compatibility flags

### ISSUE THREAD

**Issue by vkz** [vkz/bemhtml-syntax#18]
- [x] `assertHasBlock` assert that every template has sub-predicate matching `block`
- [x] `assertNoThisElem` assert there're no predicates matching `this.elem` https://github.com/bem/bem-xjst/issues/89
- [ ] `applySetsMode` assert that every `apply` sets the mode as its first argument https://github.com/bem/bem-xjst/issues/91
- [ ] `applyCheckFields` warn when `apply` assigns `block`, `elem`, `mods`, `elemMods` https://github.com/bem/bem-xjst/issues/73
- [x] `returnFromDef` ensure there's always `return` in `def` mode. Insert `return ''` when there is none
- [x] `assertNoBuf` assert `this._buf` is never used in templates

**Comment by vkz** [comment]
`applySetsMode` and `applyCheckFields` are just checks that only `warn`, never `assert`. Both work but I'm not adding them to test-suite explicitly (for now).
